### PR TITLE
Support NixOS 19.09 for <dell/xps/15-7590>

### PR DESCRIPTION
**Pull request by 9999years**
Virtual console options were renamed in 20.03; use `console.earlySetup` or `boot.earlyVconsoleSetup` depending on OS version.

Follows discussion in https://github.com/NixOS/nixos-hardware/pull/114#discussion_r374953204

### CODE REVIEW

**Comment by Mic92** [comment]
Could you also cherry-pick and test https://github.com/NixOS/nixos-hardware/pull/143 ?

**Comment by Mic92** [comment]
Has a merge conflict now.

**Comment by Mic92** [comment]
ping?

**Comment by 9999years** [comment]
Fixed the merge conflict. (Sorry for the delay, I've been busy.)

**Pull request merged**
