### PR TITLE
linux_surface kernel 5.10.19->5.13.4

### LINKED ISSUE #289: Surface Pro 4 touchscreen not working, kernel update should fix
I'm getting this issue exactly: https://github.com/linux-surface/linux-surface/issues/407. Based on the last two comments in that thread, it looks like the solution is to update the kernel. We are on 5.10.19 and they reported resolution when going from 5.10.x to 5.11.x. 

@mexisme can you do this?

### PR DESCRIPTION
**Pull request by devins2518**
cc: @mexisme

Updated kernel version to 5.13.4. I've been able to build and run it for a few hours and it's working fine on my Surface Pro 4 so far. Haven't tested a lot but it should work fine. 

Should fix #289. cc: @BentonEdmondson

### CODE REVIEW

**Comment by mexisme** [comment]
> cc: @mexisme
> 
> Updated kernel version to 5.13.4. I've been able to build and run it for a few hours and it's working fine on my Surface Pro 4 so far. Haven't tested a lot but it should work fine.
> 
> Should fix #289. cc: @BentonEdmondson

Thanks.  I simply ran out of hours in a week.
I'll try it out on my Surface Go later this week, too.

**Comment by BentonEdmondson** [comment]
Thanks! I'll test it out right now

**Comment by devins2518** [comment]
I've run into an issue originating from ipst I believe. My screen went black for a few seconds, and hitting the power button didn't turn it back on. Here are the logs:
```
Aug 03 08:58:04 devin kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Aug 03 08:58:04 devin kernel: OOM killer disabled.
Aug 03 08:58:04 devin kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Aug 03 08:58:04 devin kernel: printk: Suspending console(s) (use no_console_suspend to debug)
Aug 03 08:58:04 devin kernel: ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Stopping IPTS
Aug 03 08:58:04 devin kernel: intel_pch_thermal 0000:00:14.2: CPU-PCH is cool [31C], continue to suspend
Aug 03 08:58:04 devin kernel: ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Command 0x80000007 failed: 14
Aug 03 08:58:04 devin kernel: ACPI: EC: interrupt blocked
Aug 03 08:58:04 devin kernel: ACPI: EC: interrupt unblocked
Aug 03 08:58:04 devin kernel: OOM killer enabled.
Aug 03 08:58:04 devin kernel: Restarting tasks ...
Aug 03 08:58:04 devin kernel: ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
Aug 03 08:58:04 devin kernel: done.
Aug 03 08:58:04 devin systemd-logind[690]: Lid opened.
Aug 03 08:58:04 devin kernel: ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 1B96:006A ready
Aug 03 08:58:04 devin systemd-sleep[57190]: System resumed.
Aug 03 08:58:04 devin kernel: PM: suspend exit
Aug 03 08:58:04 devin systemd[1]: systemd-suspend.service: Succeeded.
```

**Comment by Mic92** [comment]
@devins2518 ok. let me know when you think the kernel runs stable.

**Comment by devins2518** [comment]
Been using it for about 6 hours now without facing that issue. I had some mouse lag when I was rebuilding kernel for nixpkgs update but I think that was happening previously too sometimes so not really a regression

**Comment by BentonEdmondson** [comment]
Yeah I used it for about 4 hours and it was working fine

**Comment by devins2518** [comment]
@mexisme if it looks good to you, ill reopen this

**Comment by devins2518** [comment]
Been working fine for 6 days now, havent faced that issue with ipst again so it might have just been a one off issue.

**Comment by BentonEdmondson** [comment]
Thanks for doing this

**Comment by mexisme** [comment]
> @mexisme if it looks good to you, ill reopen this

No, you're doing the right thing.
But thanks for trying to give me the opportunity to respond.

**Pull request merged**
