### PR TITLE
Add suspend workaround for Framework AMD

### PR DESCRIPTION
**Pull request by tlvince**
###### Description of changes

As of firmware v03.03, a bug in the EC causes the system to wake if AC is connected _despite_ the lid being closed. Or suspending via software e.g. `systemctl suspend` (with the lid open), then closing the lid causes the system to wake.

The following works around this, with the trade-off that keyboard presses also no longer wakes the system. See [Framework AMD Ryzen 7040 Series lid wakeup behavior feedback](https://community.frame.work/t/tracking-framework-amd-ryzen-7040-series-lid-wakeup-behavior-feedback/39128/45).

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
We moved this profile in https://github.com/NixOS/nixos-hardware/pull/776
Please rebase.

**Comment by tlvince** [comment]
Done

**Comment by endgame** [comment]
I've added a config option in https://github.com/tlvince/nixos-hardware/pull/1, so hopefully @tlvince can pull that in and then maintainers can help him get the option name/layout/etc to match repo conventions.

**Comment by endgame** [comment]
Oh, and: if this workaround is applicable to the 16in ryzen frameworks, the config option and the organisation of these modules might need to change.

**Comment by tlvince** [comment]
Thanks. The 16" isn't released yet and I suspect this'll be addressed in a firmware update at some point.

**Pull request merged**
