### PR TITLE
README: add links to docs

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Sure, but I would link the model name itself to link to the docs instead of adding another column. I'm going to rebase that on top of master.

**Comment by zimbatm** [comment]
Good idea. Any idea on how to implement it without destroying the ASCII formatting of the table?

**Comment by yegortimoshenko** [comment]
Merged in 008eb393030b414953596e2434c8b80c3762b10b.

**Comment by yegortimoshenko** [comment]
@zimbatm: I don't think there is a way to do that without destroying ASCII formatting, but if you use Org mode, at least Emacs version hides link formatting, and it looks nice. There is also a Vim port but I don't know if it does that or not.

**Comment by zimbatm** [comment]
Ack. As a note, I quite like the AsciiDoctor format because it's close to MarkDown but it better specified and has support for all the useful things like TOC, tables, link references, ..

**Comment by yegortimoshenko** [comment]
I'm going to check it out. Thanks!

**Pull request closed without merging**
