### PR TITLE
gpd/pocket-3: init

### PR DESCRIPTION
**Pull request by nbraud**
## New configuration for the GPD Pocket 3 computer
- [x] necessary kernel modules are set;
- [x] suspend-to-RAM is configured to use ACPI S2 sleep (S3 currently broken due to a firmware issue) ;
- [x] `snd-intel-dspcfg` driver is configured for audio to work on the 1195G7 model;
- [x] video drivers and hardware codec acceleration are configured;
- [x] kernel & fontconfig parameters are set to deal with the sideways & hiDPI screen.

This should presumably wait until NixOS/nixpkgs#194594 is merged, as I made the
workaround for `fonts.fontconfig.antialias` conditional on nixpkgs version.

## Potential TODOs
- Sideway screen
  - [x] Find why the `video=` kernel cmdline setting is insufficient for `sway` to orient correctly.
  - [ ] Fix touchscreen input orientation
  - [ ] Test under X.org too.
- [ ] Add support / automatic rotation when flipping the screen over (tablet mode)
- [ ] Test the webcam
- [ ] Help get support for the [fingerprint sensor](https://gitlab.freedesktop.org/libfprint/wiki/-/issues/47)
- [ ] Find someone to test with the N6000 model (which I do not own) or sponsor one.

### CODE REVIEW

**Comment by nbraud** [comment]
I think this can go in despite the open TODOs, and be improved in later PRs.

**Comment by Mic92** [comment]
Please undraft when the nixpkgs PR is merged.

**Comment by Mic92** [comment]
bors try

**Review by Mic92 — COMMENTED** [review]
Please also add the module to flake.nix and the README file as we do for the other nixos modules.

**Comment by nbraud** [comment]
@Mic92: Done, thanks for the feedback

**Comment by nbraud** [comment]
> Find why the `video=` kernel cmdline setting is insufficient for `sway` to orient correctly.

It looks like a bug in `wlroots`:
- `modetest` reports the `panel_orientation` KMS property is 3 (“right side up”) as expected,
- according to `sway`'s debug output, `wlr_drm_connector_get_panel_orientation` returns 0 (“normal” orientation).


I'll debug that further tomorrow, then open an issue against `wlroots` or submit
a patch.  Either way, this means the problem isn't in this PR.

**Comment by miangraham** [comment]
@nbraud Out of curiosity, did you ever get sway to rotate correctly based on the panel_orientation param or do you still have a transform setting on the WM side? I think I'm seeing the same thing with sway on Pocket 4 and want to make sure I'm not missing an easy solution.

Thanks for your work on this. Pocket 4 works great with similar options after pulling out the Intel-specific bits.

**Pull request merged**
