### PR TITLE
dell-xps-15-7590: remove 20.03 compat

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
cc @tomberek

**Comment by Mic92** [comment]
Also is there an update regarding the wifi firmware?

**Comment by raboof** [comment]
> Also is there an update regarding the wifi firmware?

(I have a 7590, but never really got into nixos-hardware - if there's anything simple you'd like me to check just shout ;) )

**Comment by Mic92** [comment]
@raboof this module does the following:

```
# The 48.ucode causes the Killer wifi card to crash.
  # The iwlfwifi-cc-a0-46.ucode works perfectly
  nixpkgs.overlays = [
    (self: super: {
      firmwareLinuxNonfree = super.firmwareLinuxNonfree.overrideAttrs (old: {
        src = super.fetchgit {
          url =
            "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git";
          rev = "bf13a71b18af229b4c900b321ef1f8443028ded8";
          sha256 = "1dcaqdqyffxiadx420pg20157wqidz0c0ca5mrgyfxgrbh6a4mdj";
        };
        postInstall = ''
          rm $out/lib/firmware/iwlwifi-cc-a0-48.ucode
        '';
        outputHash = "0dq48i1cr8f0qx3nyq50l9w9915vhgpwmwiw3b4yhisbc3afyay4";
      });
    })
  ];
```

Do you also have a wifi card from Killer and if so does it crash for you still?

**Comment by raboof** [comment]
I have this one:
```
3b:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
	Subsystem: Rivet Networks Device 1654
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at ed400000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
```
... so I guess not?

**Pull request merged**
