### PR TITLE
init: omen-15-en1007sa

### PR DESCRIPTION
**Pull request by sjcobb2022**
###### Description of changes

Added support for the Omen 15-en1007sa. This includes the correct BusID's and configuration. Also copying the hp-wmi config from the omen-15-en0010ca config.

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by sjcobb2022** [comment]
I would also like to add that it may be a good idea to update the naming schema for the omen-en00015p. en00015p is not reflective of the model name of any omen product that I can find. 

Most likely, this product ID is referring to [this](https://support.hp.com/us-en/product/details/omen-15-en0000-laptop-pc-series/model/35335114) model of HP omen laptop.

I can make an issue if we fix this.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@sjcobb2022 
would you mind adding these options?

```
trace: warning: For full Darter Pro support, set the options:
- hardware.system76.darp76.soundVendorId                       
- hardware.system76.darp76.soundSubsystemId                    
You can copy these values directly from:                       
- /sys/class/sound/hwC0D0/vendor_id                            
- /sys/class/sound/hwC0D0/subsystem_id
```

**Comment by sjcobb2022** [comment]
> @sjcobb2022 
> would you mind adding these options?
> 
> ```
> trace: warning: For full Darter Pro support, set the options:
> - hardware.system76.darp76.soundVendorId                       
> - hardware.system76.darp76.soundSubsystemId                    
> You can copy these values directly from:                       
> - /sys/class/sound/hwC0D0/vendor_id                            
> - /sys/class/sound/hwC0D0/subsystem_id
> ```                  

Is this a system 76 specific thing?

If so I don't have a system 76 device.

I can update the Nvidia stuff though

**Pull request merged**
