### PR TITLE
Revert "starfive visionfive2: use mainline kernel"

### PR DESCRIPTION
**Pull request by NickCao**
Reverts NixOS/nixos-hardware#958

### CODE REVIEW

**Comment by NickCao** [comment]
In absence of a quick fix, let's do a revert. https://github.com/NixOS/nixos-hardware/pull/958/commits/71a9c38d6145970a5a0e6b331b6727b90378d078 is kept though, please test.

**Comment by NickCao** [comment]
cc @malteneuss @0x4A6F

**Review by Mic92 — APPROVED** [review]

**Comment by malteneuss** [comment]
Seems to work without the qspi patch. I tried booting in QSPI and SDIO mode afterwards. Both worked:
```shell
$ nix flake lock --update-input nixos-hardware
• Updated input 'nixos-hardware':
    'github:NixOS/nixos-hardware/806e9d4a933dd1e75592e88894d4bd2f296f5bbf' (2024-05-28)
  → 'github:NixOS/nixos-hardware/8251761f93d6f5b91cee45ac09edb6e382641009' (2024-05-29)
....
$ uname -a
Linux visionfive2 6.6.0 #1-NixOS SMP Tue Jan  1 00:00:00 UTC 1980 riscv64 GNU/Linux

$ sudo visionfive2-firmware-update-flash
Erasing blocks: 35/35 (100%)
Writing data: 137k/137k (100%)
Verifying data: 137k/137k (100%)
Erasing blocks: 249/249 (100%)
Writing data: 994k/994k (100%)
Verifying data: 994k/994k (100%)
```

**Comment by NickCao** [comment]
> @NickCao Do you know when you will get another Visionfive2 board? Would probably be a lot faster to fix Nix issues. 

Should be within a few days. 

> And would you know who to ask for all potentially missing upstream kernel patches?

https://rvspace.org/en/project/JH7110_Upstream_Plan is my source to go. I think it's more about the kernel config than missing patches though.

**Pull request merged**
