### PR TITLE
microsoft/surface: add serial dev bus config

### PR DESCRIPTION
**Pull request by chisui**

### CODE REVIEW

**Comment by Mic92** [comment]
@mexisme  @devins2518 @tomberek  for review

**Comment by devins2518** [comment]
I don't have a surface 1, and my keyboard has been working fine, so I'll be unable to test. Still, the pr lgtm.

**Review by willjr — COMMENTED** [review]
Sorry for the delay, it has been a bit manic.

LGTM

**Comment by mexisme** [comment]
> LGTM

It's been a bit manic, here, as shown by my using the wrong GH account to reply...
😬

**Pull request merged**
