### PR TITLE
microsoft/surface:  Update to kernel 6.10.10

### PR DESCRIPTION
**Pull request by mexisme**
###### Description of changes

Update the default kernel to 6.10.10

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by 8bitbuddhist** [comment]
Can confirm this works on my SP9

**Comment by mexisme** [comment]
Side note:

The special ath10k driver-install code for Surface Go (et al) in https://github.com/NixOS/nixos-hardware/tree/master/microsoft/surface/surface-go/firmware/ath10k looks like it might've been obsoleted at some point this year, but I only noticed it when trying to upgrade my device from kernel 6.9 to 6.10.

I will probably add a deprecation warning for that code in the next few weeks, to then remove it probably by the time 6.11 / 6.12 kernel is added here.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
Unsure how the merge conflict is supposed to be solved.

**Comment by 8bitbuddhist** [comment]
> Unsure how the merge conflict is supposed to be solved.

I think the `ath10k-firmware` section is conflicting with #1187, which removed it

**Comment by 8bitbuddhist** [comment]
I tried out 6.11.4 with a new branch based on @nickodei's work, and so far it's been working well on my SP9. I'd be up for creating a separate PR, but it might conflict with this one. @mexisme would you like any help in getting this one resolved?

**Comment by mexisme** [comment]
> > Unsure how the merge conflict is supposed to be solved.
> 
> I think the `ath10k-firmware` section is conflicting with #1187, which removed it

Ugh, sorry, that's definitely my fault.

I'd be happy to abandon this one for #1212, since it's a much more recent kernel — assuming that would merge more cleanly, @8bitbuddhist ?

**Comment by mexisme** [comment]
Closing in favour of #1212

**Pull request closed without merging**
