### PR TITLE
asus-rog-strix-g713ie: init

### PR DESCRIPTION
**Pull request by Sigmanificient**
###### Description of changes

Set GPU pins for asus rog-strix g713ie

###### Things done

- [X] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by superherointj** [comment]
I think you may have to also add an entry to `flake.nix`.

**Comment by superherointj** [comment]
I'm new here. So I could be wrong.
But I'd keep a single commit and name it as: `asus-rog-strix-g713ie: init`
Mostly because that's the flake reference.

**Comment by superherointj** [comment]
Also test running:

> ./tests/run.py './asus/rog-strix/g713ie'

**Comment by superherointj** [comment]
> The name of flake parameter is: `asus-rog-strix-g713ie` (not spaces)

Sorry about mentioning such a small detail. =/

**Comment by Sigmanificient** [comment]
> At commit message, I'd use as name: `asus-rog-strix-g713ie` (no spaces)
> 
> image
> 
> Sorry about mentioning such a small detail. =/

it's all good, don't worry

**Comment by Sigmanificient** [comment]
CI reports:
```
 The following 1 test(s) failed:
./tests/run.py 'lenovo/thinkpad/z/gen2/z13'
```

**Comment by superherointj** [comment]
> CI reports:
> 
> ```
>  The following 1 test(s) failed:
> ./tests/run.py 'lenovo/thinkpad/z/gen2/z13'
> ```

Yes, I've opened a PR fixing it here:

https://github.com/NixOS/nixos-hardware/pull/1048

Needs someone to approve this.

**Comment by superherointj** [comment]
> Your fix has been open for 2 days already in need of review/merge ;)
> 
> #1042

I'm sorry.

**Comment by superherointj** [comment]
Please rebase to fix CI.

**Review by superherointj — APPROVED** [review]

**Pull request merged**
