### PR TITLE
framework: add framework-tool

### PR DESCRIPTION
**Pull request by pinage404**
###### Why should we want this changes ?

Recently, Framework released an update of the Framework 16 BIOS

With their open source tool, it's easy to check which version i am using

```sh
sudo framework_tool --driver portio --info
```

###### Description of changes

1. minor refactoring: move CPU folder items as it does not define CPU configuration only
2. install `framework-tool` on each Framework

###### Things done

I only tested for the Framework 16 because i don't have a Framework 13

- [x] Tested the changes in [your own NixOS Configuration](https://gitlab.com/pinage404/dotfiles/-/commit/4ea7cc3caa480c34ffd3fbd5c7f2ba8be9fa28a3)
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it ~~via `<nixos-hardware>`~~ or _Flake input_

### CODE REVIEW

**Comment by pinage404** [comment]
i don't understand why the pipeline fails

i need help to fix it

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
Check out the new CI error. Should be easier to understand now.

**Comment by pinage404** [comment]
Thanks !

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
