### PR TITLE
lenovo: fix unstable wifi on Yoga laptops

### PR DESCRIPTION
**Pull request by Jdogzz**
###### Description of changes
Add extra modprobe options to fix unstable wifi on Yoga laptops.

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify queue

**Comment by me00001** [comment]
Hello @Jdogzz 
Is this change really needed? I also have this device and the wifi is stable.

**Comment by Mic92** [comment]
@Jdogzz @me00001 I think you need to fight this out. I can't really verify this.

**Comment by Jdogzz** [comment]
> Hello @Jdogzz Is this change really needed? I also have this device and the wifi is stable.

Per the arch wiki this addresses common issues with wifi stability on these devices: https://wiki.archlinux.org/title/Network_configuration/Wireless#RTW89

Is there a more standard way of addressing issues like this?

**Pull request merged**
