### PR TITLE
16ach6h: Various fixes

### LINKED ISSUE #628: Lenovo Legion 5 Pro 16ach6h breaks when using modesetting with current config
Opening this up to see how to go about fixing it.

The commit https://github.com/NixOS/nixos-hardware/commit/630a8e3e4eea61d35524699f2f59dbc64886357d switched the default AMD driver from `amdgpu` to `modesetting`. When updating past this commit Xorg does not boot up correctly on my machine in hybrid/offload mode: https://gist.github.com/4JX/37d35bf95970f96ad341658da7af0ecd, with the Xorg config that is created being https://gist.github.com/4JX/ec3b37198fdc5900ac258ca99ce0e068.

If I manually remove the layout/device/screen referencing `amdgpu` (Created due to the presence of `hardware.nvidia.prime.amdgpuBusId`. Where any duplicate entries for drivers, from both `amdgpu` or `modesetting`, that will eventually end up controlling the iGPU trigger this issue if at least one of them uses the `modesetting` driver.) and move the `BusID` to the modesetting section (not necessary, there for redundancy) it boots up just fine.

I'm not sure if a proper fix would be to just tell it to use the `amdgpu` driver for my device, as it seems that the NixOS option is also to blame (it only considers modesetting for [intel cards](https://github.com/NixOS/nixpkgs/blob/0b530a72bd17b3cb83923f3d3e1165726902a78b/nixos/modules/hardware/video/nvidia.nix#L247) despite the move towards ditching the other drivers https://github.com/NixOS/nixpkgs/pull/218437).

### PR DESCRIPTION
**Pull request by 4JX**
###### Description of changes

A few commits to fix various annoyances I had with the config.

Fixes #628 and #795

Before merging I'd like to discuss the following the various people using this config the fact that the currently selected `amdgpuBusId = "PCI:06:00:0"` will only work for people who have two drives installed, while those that have one need to select `PCI:05:00:0` (see also https://github.com/NixOS/nixos-hardware/issues/786#issuecomment-1890439075 for a similar case, this was also brought up to my attention a long time ago on discord with the same issue)

If I had to choose a "sane default" that would be to do `lib.mkDefault "PCI:05:00:0"` with an accompanying note to set this manually for 2 drive users, but I wanted to hear your thoughts about it.

^ cc @LostAttractor @afreakk @piousdeer 

###### Things done

- [X] Tested the changes in your own NixOS Configuration
- [X] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by piousdeer** [comment]
Indeed, the correct default value for unmodified laptops is `PCI:05:00:0`.

**Comment by Mic92** [comment]
I think adding a hint in a README file for this model will be the best way forward.

**Comment by 4JX** [comment]
That should do it, works just fine with my my multiple drive laptop and a simple [config update](https://github.com/4JX/nixos-config/commit/2c7aebedc8c09bbc4aab77373da290ce492d4807).

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
