### PR TITLE
intel gpu: only enable xe driver starting with lunar lake

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
cc @fidgetingbits

**Comment by fidgetingbits** [comment]
Changes look okay to me, although not tested it as on mobile atm.

My tiger lake asus laptop is using xe without explicitly using force probe, so not sure how that works if other models are requiring force probe.. maybe the whitelist mentioned in the other issue?

I don't plan to go back to i915 on my tiger lake laptop as I haven't had any issues with xe. Seems like it would be useful to have an option to still enable it on tiger lake.

**Comment by Mic92** [comment]
Your chipset is probably in this whitelist: https://github.com/torvalds/linux/blob/ad46e8f95e931e113cb98253daf6d443ac244cde/drivers/gpu/drm/xe/xe_reg_whitelist.c#L26C37-L26C55
We can also override the driver again for your laptop model only as it uses the driver without any force option.

**Comment by Mic92** [comment]
I added it back for zenbook.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
