### PR TITLE
surface: linux-surface 6.6.25 -> 6.8.6

### LINKED ISSUE #877: Update surface-kernel to 6.7
Please update surface-kernel to kernel 6.7
https://github.com/linux-surface/linux-surface/releases/tag/fedora-38-6.7.6-1
@mexisme @damianoognissanti

### PR DESCRIPTION
**Pull request by tracteurblinde**
###### Description of changes
Updates the surface kernel/patchset to ~~6.8.1~~ 6.8.6. Replaces #878 and fixes #877.

Passes ad-hoc testing on my SLS1.

@Mic92 @mexisme @stigtsp @iwanders

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by iwanders** [comment]
Passes smoke test on my SP9, thanks!

**Comment by stigtsp** [comment]
Can this be updated to the latest 6.8 version?

**Comment by tracteurblinde** [comment]
> Can this be updated to the latest 6.8 version?

As in 6.8.6? I used 6.8.1 since that was the last tag in the `linux-surface` repo. I can see how the `arch-6.8.1-1` patchset applies on 6.8.6.

**Comment by mexisme** [comment]
> > Can this be updated to the latest 6.8 version?
> 
> As in 6.8.6? I used 6.8.1 since that was the last tag in the `linux-surface` repo. I can see how the `arch-6.8.1-1` patchset applies on 6.8.6.
> 
> Edit: Not cleanly.

`linix-surface` does update their patches fairly quickly, and you're absolutely correct to follow their latest release rather than the official kernel's.
Because (AFAICT) `linux-surface` supports more versions of Surface devices than the official kernel.

**Comment by mexisme** [comment]
> ###### Description of changes
> Updates the surface kernel/patchset to 6.8.1. Replaces #878 and fixes #877.
> 
> Passes ad-hoc testing on my SLS1.
> 
> @Mic92 @mexisme @stigtsp @iwanders
> 
> ###### Things done
> 
> - [x] Tested the changes in your own NixOS Configuration
> - [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
>       importing it via `<nixos-hardware>` or Flake input
> 
> 

I'm not sure if I'll get a chance to try this, this week, though I def. endorse moving to the 6.8.x series!

However, I now only have an older Surface Go, so I'm also not sure if this is as useful a testing target any more?

One additional thought is that I think 6.8.2 as well as one of 6.8.3 or 6.8.4 incl. some important regression fixes that would be very useful to have?

**Comment by tracteurblinde** [comment]
Updated this PR to 6.8.6

The `linux-surface` repo released 6.8.6 yesterday and updated this PR to match.

Still passes smoke testing on my SLS1.

**Review by stigtsp — APPROVED** [review]
LGTM, tested on Surface Laptop 4 AMD

**Comment by stigtsp** [comment]
@mergify queue

**Comment by stigtsp** [comment]
@Mic92 hope you don't mind me merging in this repo :)

**Comment by stigtsp** [comment]
@tracteurblinde A minor nitpick for later, the commit messages should include a "from" verison as well. This is very useful to have when cherrypicking etc.

For example:

`surface: linux-surface to 6.8.1` should be `surface: linux 6.6.25 -> 6.8.1`

Thx again! :)

**Comment by iwanders** [comment]
Late to the party, but confirming `6.8.6` works on my SP9. Thanks.

**Pull request merged**
