### PR TITLE
Add kernel 6.1.3 to Microsoft Surface profile

### PR DESCRIPTION
**Pull request by mexisme**
###### Things done

Updates the kernel version + upstream patches from [linux-surface](https://github.com/linux-surface/linux-surface) to `6.1.3`

- [ ] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by mexisme** [comment]
Hmm, seems like it's failing similarly to https://github.com/NixOS/nixos-hardware/pull/533#issuecomment-1376497418, @Mic92.

Not sure if you want me to raise an issue against some of the RasbPi commiters?

**Comment by mexisme** [comment]
If this version builds + runs as expected, I intend to drop the 6.0.* kernel.

cc @damianoognissanti, @tmnvanderberg, @Yeshey

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors cancel

**Comment by mexisme** [comment]
Kernel 6.1.6 patches have been released.
A new PR for that is here: #545

**Pull request closed without merging**
