### PR TITLE
pc/laptop: fix evaluation on 20.09

### PR DESCRIPTION
**Pull request by Mic92**
fixes https://github.com/NixOS/nixos-hardware/issues/268

### CODE REVIEW

**Comment by Mic92** [comment]
Please test @pnelson

**Comment by alyssais** [comment]
Do you mean 20.09?

**Comment by Mic92** [comment]
Right both actually.

**Comment by alyssais** [comment]
Commit message is still wrong :)

**Comment by Mic92** [comment]
Fixed message with squash on merge.

**Comment by pnelson** [comment]
Works great! Thanks @Mic92.

**Pull request merged**
