### PR TITLE
xps/13-9310: remove custom patches

### PR DESCRIPTION
**Pull request by terinjokes**
The Linux kernel now has wireless patches upstreamed into the Linux
kernel. We can remove our custom build, but preserve enabling the
bluetooth drivers.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Nice one @terinjokes!

Now just the kernel config patches to upstream, then we can finally benefit from the cached kernel builds! I'll probably try looking into this at some point when I have a bit more time, but if anyone else reading this wants to have a go and beat me to it that would be awesome :)

**Comment by mitchmindtree** [comment]
> Everything is working fine for me on 5.12.19.

I switched back to the stable channel after NixOS 21.05 was released - the stable channel appears to be building `5.12.7`. You must be on the unstable channel right?

Anyway I'll see how the `5.12.7` build goes and report back. I guess stable will catch up eventually either way!

**Comment by mitchmindtree** [comment]
No luck with `5.12.7` unfortunately, it seems the wifi patches still hadn't made it in by that point. I've switched back to `5.10.18` for now.

Do you happen to know what the policy is for the nixpkgs stable channel and kernel versions? I guess if the `nixos-21.05` stable channel is currently on `5.12.7` then it should eventually update to `5.12.19` as it's just a patch version update?

**Comment by mitchmindtree** [comment]
Agh sorry for all the noise - it seems that indeed, `5.12.19` **is** available via `linuxPackages_5_12` on the `nixos-21.05` channel - I just hadn't updated my channel in a while. Building this now!

**Comment by mitchmindtree** [comment]
My wifi still isn't working on `5.12.19` - here's the system I'm running:

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.05.1759.91903ceb294 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.05.1759.91903ceb294"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Bluetooth seems to work, but no luck with wifi - here's the `ath11k` entries in dmesg:
```
$ dmesg | grep -e ath11
[    3.937129] ath11k_pci 0000:72:00.0: BAR 0: assigned [mem 0xa2500000-0xa25fffff 64bit]
[    3.937147] ath11k_pci 0000:72:00.0: enabling device (0000 -> 0002)
[    4.203596] ath11k_pci 0000:72:00.0: chip_id 0x0 chip_family 0xb board_id 0xff soc_id 0xffffffff
[    4.207005] ath11k_pci 0000:72:00.0: fw_version 0x101c06cc fw_build_timestamp 2020-06-24 19:50 fw_build_id 
[    9.291281] ath11k_pci 0000:72:00.0: qmi failed set mode request, mode: 0, err = -110
[    9.291293] ath11k_pci 0000:72:00.0: qmi failed to send wlan fw mode:-110
[    9.291297] ath11k_pci 0000:72:00.0: failed to attach wmi: -110
[    9.291305] ath11k_pci 0000:72:00.0: failed to start core: -110
[   20.250729] ath11k_pci 0000:72:00.0: firmware crashed: MHI_CB_SYS_ERROR
```

Maybe it's a difference in system firmware? @terinjokes which version are you on? If I run `fwupdmgr get-devices` I appear to be on 2.1.1, but it looks like there have been a few releases since then: https://fwupd.org/lvfs/devices/com.dell.ueficfb08d7c.firmware

**Comment by terinjokes** [comment]
```
~ » nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.11pre304061.dd14e5d78e9 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(terin): `"home-manager-21.05"`
 - channels(root): `"nixos-21.11pre304061.dd14e5d78e9, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
 
 ```
 ~ » dmesg | grep -e ath11
[   19.872599] ath11k_pci 0000:72:00.0: BAR 0: assigned [mem 0xa2500000-0xa25fffff 64bit]
[   19.872617] ath11k_pci 0000:72:00.0: enabling device (0000 -> 0002)
[   20.380168] ath11k_pci 0000:72:00.0: chip_id 0x0 chip_family 0xb board_id 0xff soc_id 0xffffffff
[   20.380171] ath11k_pci 0000:72:00.0: fw_version 0x101c06cc fw_build_timestamp 2020-06-24 19:50 fw_build_id
```

I'm running System Firmware `3.0.3`.

**Comment by mitchmindtree** [comment]
So strange, even after updating the system firmware to `3.0.4` I'm running into the same error I posted above :thinking: I can't think of what else we might be doing differently that could be causing this, especially on the same kernel version, and the logs show the same fw version too. I might try asking in the `ath11k` mailing list to see if anyone has an idea of what might be going on.

**Comment by kbredemeier** [comment]
Just got a new 9310 with the AX500 chip and it isn't working for me either. I can observe the same behaviour as @mitchmindtree.
```
$ uname -r
5.12.19

$ dmesg | grep -e ath11
[   20.353274] ath11k_pci 0000:72:00.0: BAR 0: assigned [mem 0xa2500000-0xa25fffff 64bit]
[   20.353293] ath11k_pci 0000:72:00.0: enabling device (0000 -> 0002)
[   20.706700] ath11k_pci 0000:72:00.0: chip_id 0x0 chip_family 0xb board_id 0xff soc_id 0xffffffff
[   20.706705] ath11k_pci 0000:72:00.0: fw_version 0x101c06cc fw_build_timestamp 2020-06-24 19:50 fw_build_id
[   20.877930] ath11k_pci 0000:72:00.0 wlp114s0: renamed from wlan0
[   29.369886] ath11k_pci 0000:72:00.0: firmware crashed: MHI_CB_SYS_ERROR
[   30.287733] ath11k_pci 0000:72:00.0: failed to synchronize setup for vdev 0 start: -110
[   30.287738] ath11k_pci 0000:72:00.0: failed to start vdev 0 addr 9c:b6:d0:3f:73:d0 on freq 5580: -110
[   30.287740] ath11k_pci 0000:72:00.0: failed to delay vdev start: -110
[   30.287743] ath11k_pci 0000:72:00.0: failed to send WMI_PEER_DELETE cmd
[   30.287745] ath11k_pci 0000:72:00.0: failed to delete peer vdev_id 0 addr 74:42:7f:cc:35:62 ret -108
[   30.287747] ath11k_pci 0000:72:00.0: Failed to add station: 74:42:7f:cc:35:62 for VDEV: 0
[   30.294706] WARNING: CPU: 3 PID: 1676 at drivers/net/wireless/ath/ath11k/mac.c:5514 ath11k_mac_op_unassign_vif_chanctx+0x17e/0x1d0 [ath11k]
[   30.294758]  ip6table_nat snd_soc_acpi iptable_nat nf_nat soundwire_bus qrtr xt_conntrack ns ledtrig_audio nf_conntrack ath11k_pci nf_defrag_ipv6 nf_defrag_ipv4 snd_soc_core ath11k libcrc32c qmi_helpers ip6t_rpfilter mac80211 snd_compress ipt_rpfilter ac97_bus snd_pcm_dmaengine x86_pkg_temp_thermal intel_powerclamp coretemp snd_hda_intel ip6table_raw crc32_pclmul ghash_clmulni_intel snd_intel_dspcfg iptable_raw intel_cstate snd_intel_sdw_acpi intel_uncore xt_pkttype snd_hda_codec cfg80211 nf_log_ipv6 intel_spi_pci deflate intel_spi serio_raw efi_pstore nf_log_ipv4 snd_hda_core spi_nor nf_log_common i2c_i801 snd_hwdep xt_LOG i2c_smbus mtd snd_pcm xt_tcpudp mhi libarc4 ip6table_filter ip6_tables nls_iso8859_1 nls_cp437 vfat sch_fq_codel iptable_filter fat mei_me mei intel_lpss_pci intel_lpss msr idma64 ctr virt_dma intel_ish_ipc intel_ishtp 8250_pci processor_thermal_device processor_thermal_rfim processor_thermal_mbox processor_thermal_rapl intel_rapl_common thunderbolt tpm_crb intel_pmt
[   30.294883] RIP: 0010:ath11k_mac_op_unassign_vif_chanctx+0x17e/0x1d0 [ath11k]
[   30.295099] ath11k_pci 0000:72:00.0: failed to submit WMI_VDEV_STOP cmd
[   30.295101] ath11k_pci 0000:72:00.0: failed to stop WMI vdev 0: -108
[   30.295103] ath11k_pci 0000:72:00.0: failed to stop vdev 0: -108
[   34.400084] ath11k_warn: 8 callbacks suppressed
[   34.400093] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   34.400101] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   35.401594] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   35.401605] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   36.402771] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   36.402777] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   37.403763] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   37.403772] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   38.405082] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   38.405092] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   39.406466] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   39.406475] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   40.407871] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   40.407881] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   41.408817] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   41.408822] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   42.409780] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   42.409790] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   43.411248] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   43.411257] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   44.411773] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   44.411783] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   45.413218] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   45.413228] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   46.414747] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   46.414758] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   47.416256] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   47.416266] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   48.417604] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   48.417615] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   49.419014] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   49.419023] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   50.420500] ath11k_pci 0000:72:00.0: failed to send WMI_START_SCAN_CMDID
[   50.420512] ath11k_pci 0000:72:00.0: failed to start hw scan: -108
[   51.007168] ath11k_pci 0000:72:00.0: fail to set monitor filter: -108
[   51.007308] ath11k_pci 0000:72:00.0: failed to submit WMI_VDEV_DELETE_CMDID
[   51.007313] ath11k_pci 0000:72:00.0: failed to delete WMI vdev 0: -108
[   51.007318] ath11k_pci 0000:72:00.0: removing stale peer 74:42:7f:cc:35:62 from vdev_id 0
[   51.007350] ath11k_pci 0000:72:00.0: failed to clear rx_filter for monitor status ring: (-108)
[   51.016668] ath11k_pci 0000:72:00.0: failed to send WMI_PDEV_SET_PARAM cmd
[   51.016680] ath11k_pci 0000:72:00.0: failed to enable PMF QOS: (-108
[  378.669088] ath11k_pci 0000:72:00.0: failed to send WMI_PDEV_SET_PARAM cmd
[  378.669095] ath11k_pci 0000:72:00.0: failed to enable PMF QOS: (-108
[  791.014055] ath11k_pci 0000:72:00.0: failed to send WMI_PDEV_SET_PARAM cmd
[  791.014064] ath11k_pci 0000:72:00.0: failed to enable PMF QOS: (-108
```

**Comment by Mic92** [comment]
Is reverting to the old patches helping?

**Comment by kbredemeier** [comment]
At least it's working for me if I use a revision with the patches still in place

**Comment by terinjokes** [comment]
I just switched back to stable to test, and it's still working fine here.

```
~ » uname -r
5.12.19

~ » dmesg | grep -e ath11
[   18.371348] ath11k_pci 0000:72:00.0: BAR 0: assigned [mem 0xa2500000-0xa25fffff 64bit]
[   18.371370] ath11k_pci 0000:72:00.0: enabling device (0000 -> 0002)
[   18.865001] ath11k_pci 0000:72:00.0: chip_id 0x0 chip_family 0xb board_id 0xff soc_id 0xffffffff
[   18.865006] ath11k_pci 0000:72:00.0: fw_version 0x101c06cc fw_build_timestamp 2020-06-24 19:50 fw_build_id

~ » nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.05.2075.ff1ea3a36c1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(terin): `"home-manager-21.05"`
 - channels(root): `"nixos-21.05.2075.ff1ea3a36c1, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
 
 I'm connected to a 5GHz 802.11ac network. I'm still running system firmware 3.0.3, but can try 3.0.4

**Comment by kbredemeier** [comment]
My BIOS info looks a little bit different:

* BIOS Version: 3.0.4
* Manufacture Date: 07/20/2021
* Wi-Fi Device: Qualcomm Wireless

I found [this](https://bugzilla.kernel.org/show_bug.cgi?id=210923) issue in the kernel bug tracker. According to the thread the firmware has issues if the host uses memory under the 32M limit. I was able to get the WiFi working by adding `boot.kernelParams = [ "memmap=12M\\\$20M" ];` to my system config. Not sure this is reliable yet.

**Comment by terinjokes** [comment]
I would not be surprised if in the last 9 months Dell has made subtle revisions. I can't explain why it thinks I have no wireless device. 🤔

It looks like the debug line mentioned for the memory location is enabled with `CONFIG_ATH11K_DEBUG`. I'll rebuild my kernel with that enabled so I can print mine for comparison.

**Comment by rowanG077** [comment]
I also have no wifi... Did you manage to fix anything @terinjokes

**Comment by terinjokes** [comment]
Nothing is broken here, I'm using WiFi right now.

**Comment by mitchmindtree** [comment]
OK! I managed to get my WiFi working on this commit!

After a recommendation from Kalle, I tried:
```
  boot.kernelParams = [
    "memmap=12M\$20M"
  ];
```
but with no luck. I then tried some different values they recommended:
```
  boot.kernelParams = [
    "memmap=14M\$18M"
  ];
```
and this seems to have worked!

I've no idea why these specific values were necessary in my case or what they really affect, but hopefully this helps someone else running into similar issues.

**Comment by terinjokes** [comment]
I should probably make an account in Discourse at this point. In the meantime, an FYI for everyone: looks like at least sleep and wifi are broken on 5.13.16 and higher (and unlikely to be fixed) and 5.14.4 and higher. It looks like a patch upstream is scheduled to be in 5.14.7, trying it out now.

**Comment by rowanG077** [comment]
Can confirm it works without that patch now that 5.14.7 is released.

**Pull request merged**
