### PR TITLE
Add a note about rcu_sched problems

### PR DESCRIPTION
**Pull request by boothead**
How I fixed my XPS15 after it being dead for two months

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Thank you!

**Comment by Mic92** [comment]
I like how we can express workarounds in a crisp, brief manner instead of burying the solution in a forum on page 3.

**Comment by roberth** [comment]
Hold on, this is the XPS 15 9550 page, not the XPS 15 9560, right? Although similar, they are different models.

**Comment by boothead** [comment]
Right you are @roberth - Also I notice I've screwed up the rendering (I thought I was writing markdown)

**Pull request merged**
