### PR TITLE
starfive visionfive2: allow generic image to boot on all variants of boards

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes

Tested on v1.3B 8GB version.

###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by NickCao** [comment]
Finally got access to a new board! Please test on v1.2A and 4GB versions of boards if possible.

**Comment by NickCao** [comment]
cc @malteneuss @onny @misuzu @0x4A6F

**Comment by malteneuss** [comment]
Works on 1.3b 8GB board. And looking forward to testing the latest kernel.

**Comment by onny** [comment]
Why is this patch not required anymore? Because we are already on mainline kernel? Does mainline boot without the patch?

**Comment by malteneuss** [comment]
No, because we have quite a new uboot package in nixpkgs unstable that apparently can select the visionfive2 devices on its own.

**Review by onny — APPROVED** [review]
Works for me :)
1.3b 8GB board

**Comment by NickCao** [comment]
@mergify queue

**Comment by malteneuss** [comment]
@NickCao Any luck on getting the latest Linux kernel 6.9.2 to work?

**Comment by NickCao** [comment]
> @NickCao Any luck on getting the latest Linux kernel 6.9.2 to work?

See https://github.com/NixOS/nixos-hardware/pull/964 for @onny 's attempt

**Pull request merged**
