### PR TITLE
Add config for Dell XPS 15 9520

### PR DESCRIPTION
**Pull request by palfrey**
###### Description of changes

Setup for Dell XPS 15 9520

###### Things done
- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
Please also add the configuration to the README and flake.nix

**Comment by palfrey** [comment]
> Please also add the configuration to the README and flake.nix

Done

**Comment by Mic92** [comment]
bors merge

**Comment by hoh** [comment]
Hey,

Thanks for publishing this.

I have been using the config for 15-9500 so far with success on the 15-9520 since before this PR.

The only difference between the two is the [thermal-conf.xml](https://github.com/NixOS/nixos-hardware/blob/master/dell/xps/15-9500/thermald-conf.xml), do you know why it would be relevant for the 9500 but not the 9510/9520 ?

**Pull request merged**
