### PR TITLE
chore: replace writeShellScriptBin in prime.nix with enableOffloadCmd

### PR DESCRIPTION
**Pull request by Guanran928**
option introduced in this commit:
https://github.com/NixOS/nixpkgs/commit/2a7130d13a032093f5394ef0961842d1e1928789

###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
We can potentially check for nixpkgs.config.nvidia.acceptLicense here?

**Comment by Guanran928** [comment]
I'm unfamiliar with Nix (and Git) and I don't actually know what's going on here. :/
Can you show me how to do it exactly? And I've enabled `Allow edits by maintainers`.

**Comment by Mic92** [comment]
Looks like your change doesn't affect the build issue here at all.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
