### PR TITLE
Added configuration for Lenovo IdeaPad Gaming 3 15ach6

### PR DESCRIPTION
**Pull request by penguix0**
###### Description of changes

Added configuration for Lenovo IdeaPad Gaming 3 15ach6, used it for a month or so on my system and decided to add it to this repository. This is my first time making a pull request, so please let me there is something wrong with my request.

###### Things done

- Added configuration to the appropriate directory.
- [ x ] Updated `flake.nix`
- [ x ] Updated `README.md`

- [ x ] Tested the changes in your own NixOS Configuration
- [ x ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

I also ran the test script as described in CONTRIBUTING.md

### CODE REVIEW

**Comment by superherointj** [comment]
Please, rebase to master to fix CI.

**Comment by superherointj** [comment]
git rebase upstream/master

Replace upstream with the git remote branch for your source.

**Comment by superherointj** [comment]
The revert you did is not what I said... It should be a single commit, not 3 commits.

**Comment by superherointj** [comment]
> I'm going to try this again, this is like my first week working with git cli. 

Understandable.

> Should I just delete the repository and add the files again?

No. I'd learn git first. It is going to take you about 2 hours and you are done with it (for life).

https://learngitbranching.js.org/

**Comment by superherointj** [comment]
> Okay I finished the course, it was quite helpful to be honest, thanks.

Did you do the two tabs?

image

**Comment by penguix0** [comment]
Yes, however I must say working with only the CLI and without the visualization is lot harder.

**Comment by penguix0** [comment]
Not my intention to close it but now the two commits are gone finally. Lets see if I can add everything in one commit this time.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
