### PR TITLE
thinkpad: introduce t430

### PR DESCRIPTION
**Pull request by erictapen**
Copied everything from t440p, added a fix for the brightness keys

### CODE REVIEW

**Comment by erictapen** [comment]
Ah right, added it.

**Comment by Mic92** [comment]
@yegortimoshenko do we want all repositories also to be included in https://github.com/NixOS/nixos-hardware/blob/master/default.nix#L24 ?

**Comment by erictapen** [comment]
Rebased to master due to merge conflicts.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
