### PR TITLE
Rewrite the microsoft/surface `linuxPackage` function to make it simpler to use

### PR DESCRIPTION
**Pull request by mexisme**
###### Description of changes
The original `linuxPackage` function required passing-in more metadata / params than necessary (apologies for my code!).
I rewrote it some months ago, based on a similar set of functions I use in a private repo to (hopefully) make it simpler to use.

###### Things done

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by mexisme** [comment]
cc @stigtsp @ifd3f @damianoognissanti

**Comment by damianoognissanti** [comment]
I had to manually set `microsoft-surface.kernelVersion="6.6.13";` in my `configuration.nix` for it to build. Previously you could leave it unset for the default value. 
I am building it now to see if everything works as expected. Will write again later today.

**Comment by damianoognissanti** [comment]
Btw, are there plans to cache the builds somehow? Either in the regular cache or the nix-community one? To avoid the frequent recompilations?

**Comment by damianoognissanti** [comment]
Everything seems to work on my machine. Batteries are detected (but they are with stock kernel too), the camera works (using v4l2loopback), and touchscreen too.

**Comment by mexisme** [comment]
> I had to manually set `microsoft-surface.kernelVersion="6.6.13";` in my `configuration.nix` for it to build. Previously you could leave it unset for the default value. I am building it now to see if everything works as expected. Will write again later today.

Yes, I ran out of time to find this, and just found + fixed it.
Thanks!

**Comment by mexisme** [comment]
> I had to manually set `microsoft-surface.kernelVersion="6.6.13";` in my `configuration.nix` for it to build. Previously you could leave it unset for the default value. I am building it now to see if everything works as expected. Will write again later today.

Ah, I see how that code was intended, now;  I misinterpreted the intention.
Let me fix this, now...

**Comment by mexisme** [comment]
> > I had to manually set `microsoft-surface.kernelVersion="6.6.13";` in my `configuration.nix` for it to build. Previously you could leave it unset for the default value. I am building it now to see if everything works as expected. Will write again later today.
> 
> Ah, I see how that code was intended, now; I misinterpreted the intention. Let me fix this, now...

I've fixed it (i.e. restored the functionality) so you can set the major.minor version as the default kernel-version.

**Comment by mexisme** [comment]
> Btw, are there plans to cache the builds somehow? Either in the regular cache or the nix-community one? To avoid the frequent recompilations?

IDK if the `nixos-hardware` repo is cached anywhere by default?
However, it seems to come-up every so often.

Partly perhaps because I've been told that some people would prefer the hardware-specific fixes were rolled-into the main `nixpkgs` repo — except that moves pretty slow c.f. how quickly some hardware gets support...

**Comment by damianoognissanti** [comment]
> > > I had to manually set `microsoft-surface.kernelVersion="6.6.13";` in my `configuration.nix` for it to build. Previously you could leave it unset for the default value. I am building it now to see if everything works as expected. Will write again later today.
> > 
> > 
> > Ah, I see how that code was intended, now; I misinterpreted the intention. Let me fix this, now...
> 
> I think I've fixed it — i.e. restored the functionality — so you can set the major.minor version as the default kernel-version.

After a flake update I could unset the kernelVersion and it didn't complain and didn't try to build a different version, so it's probably fixed.

**Comment by damianoognissanti** [comment]
> > Btw, are there plans to cache the builds somehow? Either in the regular cache or the nix-community one? To avoid the frequent recompilations?
> 
> IDK if the `nixos-hardware` repo is cached anywhere by default? However, it seems to come-up every so often.
> 
> Partly perhaps because I've been told that some people would prefer the hardware-specific fixes were rolled-into the main `nixpkgs` repo — except that moves pretty slow c.f. how quickly some hardware gets support...

But one also cache just the microsoft part of nixos-hardware. This is done by someone with a powerful machine (or some build system somewhere), and uploaded to the binary cache. 
Here are the instructions for the nix-community cache (but I am not sure how to get an account though): `https://app.cachix.org/cache/nix-community#push`

And sorry that this is off topic...

**Comment by mexisme** [comment]
> But one also cache just the microsoft part of nixos-hardware. This is done by someone with a powerful machine (or some build system somewhere), and uploaded to the binary cache. Here are the instructions for the nix-community cache (but I am not sure how to get an authorized account though): `https://app.cachix.org/cache/nix-community#push`
> 
> And sorry that this is off topic...

Afraid I'm not sure what the right thing to say, here, would be?

Perhaps looking into creating your own small build-cluster might help?
- https://nixos.wiki/wiki/Distributed_build
- https://nixos.org/manual/nix/stable/advanced-topics/distributed-builds.html

Desktop-style machines are almost always more performant than laptops, primarily because they can provide much better power and cooling, and even some of the very small 2nd-hand office-style machines can be surprisingly quick for the cost.

**Comment by Mic92** [comment]
> Btw, are there plans to cache the builds somehow? Either in the regular cache or the nix-community one? To avoid the frequent recompilations?

If you can help me to add a hydra jobset to this repository, we can enable hydra.nixos.org for this repository.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify merge

**Comment by Mic92** [comment]
@mergify update

**Comment by Mic92** [comment]
@mergify queue

**Comment by damianoognissanti** [comment]
> > Btw, are there plans to cache the builds somehow? Either in the regular cache or the nix-community one? To avoid the frequent recompilations?
> 
> If you can help me to add a hydra jobset to this repository, we can enable hydra.nixos.org for this repository. Than everything would land in the official binary cache.

Sure, I can try. Is there any documentation on how to add a hydra jobbset to a repository? Any template or guide?

**Pull request merged**
