### PR TITLE
starfive visionfive2: update kernel to 6.5.0-rc1

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by NickCao** [comment]
Tested building kernel. cc @0x4A6F

**Comment by 0x4A6F** [comment]
Starting `memtester 7600` still crashes the system:
```
[  135.085989] Oops - store (or AMO) access fault [#1]
[  135.086006] Modules linked in: af_packet cfg80211 rfkill 8021q xhci_pci xhci_pci_renesas xhci_hcd motorcomm usbcore imx219 cdns_csi2rx v4l2_fwnode dwmac_starfive jh7110_tdm v4l2_async stmmac_platform snd_soc_j
h7110_pwmdac_dit snd_soc_simple_card axp20x_regulator snd_soc_simple_card_utils jh7110_pwmdac snd_soc_core ofpart cmdlinepart snd_compress stmmac videodev ac97_bus snd_pcm_dmaengine spi_nor vs_drm cdns3 cdns_usb_
common roles snd_pcm pcs_xpcs mtd axp20x_i2c phylink cdns3_starfive axp20x of_mdio usb_common regmap_i2c pcie_starfive fixed_phy fwnode_mdio libphy spidev mc drm_kms_helper snd_timer clk_starfive_jh7110_vout ptp
snd dw_axi_dmac_platform starfive_wdt clk_starfive_jh7110_isp spi_cadence_quadspi jh7110_crypto pps_core pinctrl_starfive_jh7110_aon jh7110_trng phy_jh7110_dphy_rx watchdog clk_starfive_jh7110_aon i2c_designware_
platform i2c_designware_core phy_jh7110_pcie led_class rng_core virt_dma sfctemp clk_starfive_jh7110_stg crypto_engine spi_pl022 phy_jh7110_usb soundcore xt_conntrack nf_conntrack
[  135.086281]  nf_defrag_ipv6 nf_defrag_ipv4 xt_tcpudp ip6t_rpfilter ipt_rpfilter xt_pkttype nft_compat nf_tables uio_pdrv_genirq uio libcrc32c nfnetlink sch_fq_codel atkbd libps2 serio vivaldi_fmap loop tun tap
 macvlan drm bridge stp llc fuse backlight i2c_core efi_pstore firmware_class pstore configfs ip_tables x_tables autofs4 ext4 crc32c_generic crc16 mbcache jbd2 mmc_block dw_mmc_starfive dw_mmc_pltfm dw_mmc mmc_co
re dm_mod dax
[  135.086442] CPU: 0 PID: 990 Comm: memtester Tainted: G        W          6.5.0-rc1 #1-NixOS
[  135.086452] Hardware name: StarFive VisionFive 2 v1.3B (DT)
[  135.086457] epc : __memset+0x60/0x100
[  135.086474]  ra : __handle_mm_fault+0x580/0xdde
[  135.086488] epc : ffffffff80873cf0 ra : ffffffff802081c0 sp : ffffffc800683b90
[  135.086495]  gp : ffffffff8198bb20 tp : ffffffd8d2630000 t0 : ffffffd800000000
[  135.086501]  t1 : ffffffff808738d4 t2 : 0000000000000100 s0 : ffffffc800683c70
[  135.086507]  s1 : ffffffd8d47d17d8 a0 : ffffffd800000000 a1 : 0000000000000000
[  135.086512]  a2 : 0000000000001000 a3 : ffffffd800001000 a4 : 0000000000000000
[  135.086518]  a5 : 0000000040000000 a6 : 0000000000040000 a7 : ffffffffffffffff
[  135.086523]  s2 : ffffffc701000000 s3 : ffffffd8d0224840 s4 : ffffffff8198b375
[  135.086529]  s5 : ffffffd8d0224840 s6 : 0000000000102073 s7 : ffffffd8c93a7800
[  135.086535]  s8 : ffffffff8198b374 s9 : ffffffff81034dd0 s10: 0000000000000000
[  135.086540]  s11: 0000000000000000 t3 : 0000000000000080 t4 : 000000000000226c
[  135.086545]  t5 : 00000000fa83b2da t6 : 0000000000000004
[  135.086549] status: 0000000200000120 badaddr: ffffffd800000000 cause: 0000000000000007
[  135.086556] [<ffffffff80873cf0>] __memset+0x60/0x100
[  135.086567] [<ffffffff80208b8e>] handle_mm_fault+0x170/0x268
[  135.086577] [<ffffffff801ff560>] __get_user_pages+0x204/0x36e
[  135.086587] [<ffffffff80200e8e>] populate_vma_page_range+0x7e/0xea
[  135.086597] [<ffffffff80201064>] __mm_populate+0xac/0x176
[  135.086606] [<ffffffff8020cf7a>] do_mlock+0x148/0x23c
[  135.086616] [<ffffffff8020e87e>] sys_mlock+0x1a/0x22
[  135.086626] [<ffffffff8087fb20>] do_trap_ecall_u+0x142/0x156
[  135.086638] [<ffffffff80003ce4>] ret_from_exception+0x0/0x64
[  135.086661] Code: 1007 82b3 40e2 0797 0000 8793 00e7 8305 97ba 8782 (b023) 00b2
[  135.383321] ---[ end trace 0000000000000000 ]---
[  135.383327] Kernel panic - not syncing: Fatal exception in interrupt
[  135.383331] SMP: stopping secondary CPUs
[  135.398257] ---[ end Kernel panic - not syncing: Fatal exception in interrupt ]---
```

**Comment by Mic92** [comment]
I guess we should than revert. Do you want to make a pull request @0x4A6F?

**Comment by leifhelm** [comment]
@0x4A6F Have you run the `memtester` on the old kernel after this issue occurred in this kernel. I just want to make sure that your hardware has not broken in between the kernel updates. I have run `sudo memtester 7600` for multiple hours (69 iterations) just fine.

**Pull request merged**
