### PR TITLE
Microchip Icicle Kit BSP update

### PR DESCRIPTION
**Pull request by codehub8**
- Kernel upadated to 6.1.43
- Uboot updated to 2023.07.02

###### Things done

- [OK] Tested the changes in your own NixOS Configuration
- [OK] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by codehub8** [comment]
Please review.

**Comment by Mic92** [comment]
@mergify queue

**Review by codehub8 — COMMENTED** [review]
Seems OK

**Review by codehub8 — COMMENTED** [review]
Please approve and merge it.

**Comment by Mic92** [comment]
@mergify refresh

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
