### PR TITLE
starfive visionfive2: use upstream u-boot v2024.01-rc5

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by NickCao** [comment]
cc @leifhelm, please test.

**Comment by NickCao** [comment]
Also @colemickens and @6543

**Comment by NickCao** [comment]
Tested booting, and running `visionfive2-firmware-update-flash`.

**Comment by 6543** [comment]
Uh let me try that patch out :)

**Comment by leifhelm** [comment]
I can boot. However I cannot ssh into it. (can’t even ping it). I guess this is a problem of either my config or the kernel.

**Comment by Mic92** [comment]
> Tested booting. `visionfive2-firmware-update-flash` fails due to `u-boot.itb` too big to fit into `mtd1`.

Is this a blocker of this pull request?

**Comment by NickCao** [comment]
> Is this a blocker of this pull request?

Kind of, we need a fix like https://github.com/NixOS/nixos-hardware/pull/646

**Comment by leifhelm** [comment]
According to [`jh7110-starfive-visionfive-2.dtsi`](https://github.com/starfive-tech/linux/blob/JH7110_VisionFive2_upstream/arch/riscv/boot/dts/starfive/jh7110-starfive-visionfive-2.dtsi#L447) there should be 3 MiB space and `uboot.itb` is only 869 KiB. However I notice that there are 2 further partitions. Maybe we have to switch to `mtd2`?

**Comment by NickCao** [comment]
> According to [`jh7110-starfive-visionfive-2.dtsi`](https://github.com/starfive-tech/linux/blob/JH7110_VisionFive2_upstream/arch/riscv/boot/dts/starfive/jh7110-starfive-visionfive-2.dtsi#L447) there should be 3 MiB space and `u-boot.itb` is only 869 KiB. However I notice that there are 2 further partitions. Maybe we have to switch to `mtd2` if it exists?

Reasonable, the partition is also named `uboot` in stead of `uboot-env`, seemingly more appropriate for our usage.

**Review by Mic92 — APPROVED** [review]
Please run the merge queue command (mergify) when you think this is ready.

**Comment by NickCao** [comment]
> > According to [`jh7110-starfive-visionfive-2.dtsi`](https://github.com/starfive-tech/linux/blob/JH7110_VisionFive2_upstream/arch/riscv/boot/dts/starfive/jh7110-starfive-visionfive-2.dtsi#L447) there should be 3 MiB space and `u-boot.itb` is only 869 KiB. However I notice that there are 2 further partitions. Maybe we have to switch to `mtd2` if it exists?
> 
> Reasonable, the partition is also named `uboot` in stead of `uboot-env`, seemingly more appropriate for our usage.

Confirmed by vendor documentation: https://doc-en.rvspace.org/VisionFive2/Quick_Start_Guide/VisionFive2_SDK_QSG/spl_new.html

**Comment by NickCao** [comment]
@mergify queue

**Pull request merged**
