### PR TITLE
Rename omen laptop model

### PR DESCRIPTION
**Pull request by celsomiranda**
###### Description of changes
The old model name was not correct and did not match any known models for the Omen brand.

###### Things done
Renamed the folder to the correct model name

- [x] Tested the changes in your own NixOS Configuration
- [x] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by Mic92** [comment]
The CI fails because you also need to rename it in the README.md

**Comment by the-furry-hubofeverything** [comment]
Heya, while you are here, can I also get the motherboard model of the laptop?
Here's mine for example:
```
[nix-shell:~]$ sudo dmidecode -t 2 | grep -i Product
	Product Name: 8786
```

I want to see if your motherboard model is compatible with the `hp-wmi` platform drivers, models listed here https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/platform/x86/hp/hp-wmi.c?h=v6.1.58#n52

Newer Victus laptops are support in 6.5 I believe

**Comment by Mic92** [comment]
@celsomiranda sorry, Got a merge conflict again. Could you fix?

**Comment by celsomiranda** [comment]
> @celsomiranda sorry, Got a merge conflict again. Could you fix?

Sorry, it says only those with write access to this repository can resolve the conflicts.

**Comment by the-furry-hubofeverything** [comment]
I think you need to rebase the branch

**Comment by Mic92** [comment]
Yes. Run `git fetch origin` and `git rebase origin master` (assuming that origin points to https://github.com/NixOS/nixos-hardware) locally. If solving those merge conflicts is too much hassle, you can also start from current master again (it's just renaming files anyway).

**Comment by Mic92** [comment]
This pull request seems to get stalled. Please re-open, if you have time to fix the merge conflict

**Pull request closed without merging**
