### PR TITLE
add lenovo x250

### PR DESCRIPTION
**Pull request by Mic92**
Basically a meta profile that combines thinkpad + intel.

### CODE REVIEW

**Comment by zimbatm** [comment]
@Mic92 can you add a `users: Mic92` comment? That will help other users ping you in case they want to change the profile.

**Comment by Mic92** [comment]
In nixos we also have `meta.maintainers` for nixos modules

**Comment by yegortimoshenko** [comment]
Perhaps it makes sense to only enable `services.thinkfan` for ThinkPads where fan control doesn't work properly out of the box.

**Comment by zimbatm** [comment]
@yegortimoshenko I told you, generalization doesn't work on this repo. Only users of a specific hardware can test it properly.

**Comment by yegortimoshenko** [comment]
@zimbatm I disagree: apparently it works pretty well, this profile inherits ThinkPad profile, generic laptop profile, generic PC profile, and Intel CPU profile. And there is only option that is overrided specifically in this new profile, which also might go away and moved into model profiles if we decide that many ThinkPads have decent fan control by default.

**Comment by zimbatm** [comment]
The problem is not right now, it's when you want to change a setting in one of the generalized profiles. This will inevitably lead to changes that haven't be tested on the affected hardware.

**Comment by yegortimoshenko** [comment]
@zimbatm It does work on @Mic92's hardware, that daemon just might not be beneficial in case of ThinkPad X250.

**Comment by zimbatm** [comment]
It's fine, only the future will tell if my prediction are true. If you keep steering this repo it might also not happen as much as I expect it to be.

**Pull request merged**
