### PR TITLE
starfive/visionfive/v1: init

### PR DESCRIPTION
**Pull request by Madouura**
Moving from https://github.com/NixOS/nixpkgs/pull/168826.

### CODE REVIEW

**Comment by Madouura** [comment]
To build the SD image: ``nix-build "<nixpkgs/nixos>" -A config.system.build.sdImage -I nixos-config=iso.nix``
iso.nix:
```nix
{ config, ... }:

{
  imports = [ "${nixos-hardware-directory}/starfive/visionfive/v1/sd-image-installer.nix" ];

  nixpkgs.crossSystem = {
    config = "riscv64-unknown-linux-gnu";
    system = "riscv64-linux";
  };
}
```

**Comment by Madouura** [comment]
Looks like the documentation has changed.
IIRC these should be the relevant docs for flashing.
https://doc-en.rvspace.org/VisionFive/Quick_Start_Guide/VisionFive_QSG/using_xmodem1.html
https://doc-en.rvspace.org/VisionFive/Quick_Start_Guide/VisionFive_QSG/for_maclinux4.html

**Comment by Mic92** [comment]
Can you add your last two messages to a README.md in the profile directory? Than it's easier for the next person to figure out how to use the profile.

**Comment by Madouura** [comment]
```console
loading module dm_mod...
[    4.770798] device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurements will not be recorded in the IMA log.
[    4.783332] device-mapper: uevent: version 1.0.3
[    4.788525] device-mapper: ioctl: 4.47.0-ioctl (2022-07-28) initialised: dm-devel@redhat.com
running udev...
Starting version 250.4
kbd_mode: KDSKBMODE: Inappropriate ioctl for device
starting device mapper and LVM...
[   10.469265] random: crng init done
waiting for device /dev/disk/by-label/NIXOS_SD to appear.......................
Timed out waiting for device /dev/disk/by-label/NIXOS_SD, trying to mount anyway.
mounting /dev/disk/by-label/NIXOS_SD on /...
[   40.484664] /dev/disk/by-label/NIXOS_SD: Can't open blockdev
mount: mounting /dev/disk/by-label/NIXOS_SD on /mnt-root/ failed: No such file or directory

An error occurred in stage 1 of the boot process, which must mount the
root filesystem on `/mnt-root' and then start stage 2.  Press one
of the following keys:

  r) to reboot immediately
  *) to ignore the error and continue
```

As far as I can tell, this error is likely on nixpkgs' side, but I could be wrong.
I've spent the last 8 hours trying to debug this so if anyone has any better ideas until I figure it out, let me know.

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
