### PR TITLE
Dell XPS 13-9320: initial config

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

### CODE REVIEW

**Comment by FRidh** [comment]
Will integrate https://github.com/NixOS/nixos-hardware/issues/493

**Comment by FRidh** [comment]
webcam is not functioning yet. Device exists, however
```
$ dmesg | grep vsc
[   22.820495] intel vsc not ready
[   22.864168] intel vsc not ready
[   22.908654] intel vsc not ready
[   22.939531] intel vsc not ready
[   22.977289] intel vsc not ready
[   23.006503] intel vsc not ready
[   23.035352] intel vsc not ready
[   23.083736] intel vsc not ready
[   23.180047] intel vsc not ready
[   23.229893] intel vsc not ready
[   23.301121] intel vsc not ready
[   23.335356] intel vsc not ready
[   23.382618] intel vsc not ready
[   23.422891] intel vsc not ready
[   23.464175] intel vsc not ready
[   23.511399] intel vsc not ready
[   23.545464] intel vsc not ready
[   23.572535] intel vsc not ready
[   31.731382] vsc_ace spi-INTC1094:00-5db76cf6-0a68-4ed6-9b78-0361635e2447: recv firmware id
```

**Comment by Mic92** [comment]
This has a merge conflict now.

**Comment by Mic92** [comment]
Please re-open if this is ready to be merged. Thanks!

**Comment by tsndr** [comment]
Hey, I'd love to see you @FRidh finish this. I love my 9320 and would love to see it supported.

**Comment by FRidh** [comment]
Camera is still an issue. Unfortunately the linked gist does not record matching revisions. Just using latest did not work for me.

**Comment by vale981** [comment]
https://discourse.nixos.org/t/missing-ivsc-firmware-on-dell-xps-13-plus-9320/36724/2
this did it for me

**Pull request closed without merging**
