### PR TITLE
lenovo-x1: removed battery TLP threshholds

### LINKED ISSUE #98: Lenovo X1 Battery Tresholds set
In the hardware configuration file for Lenovo Thinkpad x1 6th generation, there are some configuration regarding charging thresholds.
As these are personal preference, shouldn't these be removed? 

https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/x1/6th-gen/default.nix#L18-L19

### PR DESCRIPTION
**Pull request by eyJhb**
Fixes #98 , as it should not be set.

### CODE REVIEW

**Comment by danbst** [comment]
@eyJhb can you convert removed part to module instead? 

```
{ config, lib, ... }:
{
  options.recommendations.battery.linrunner = lib.mkOption {
    description = ''
      ThinkPad battery features means battery charge thresholds and the possibility to discharge or recalibrate the battery when AC is connected.
      Disclaimer:
        ThinkPad battery features work on IBM/Lenovo ThinkPads only!
        Any other Lenovo laptop models including IdeaPads – and other laptop brands of course – are not supported. Please do not file issues for this.
        There are no additional power saving features for ThinkPads.

      See https://linrunner.de/en/tlp/docs/tlp-faq.html#battery for more details.
    '';
    default = false;
  };
  config = lib.mkIf config.recommendations.battery.linrunner {
    services.tlp.extraConfig = ''
      START_CHARGE_THRESH_BAT0=75
      STOP_CHARGE_THRESH_BAT0=80
      CPU_SCALING_GOVERNOR_ON_BAT=powersave
      ENERGY_PERF_POLICY_ON_BAT=powersave
    '';
  };
}
```

**Comment by yegortimoshenko** [comment]
Modules have been out of scope for this project (so far).

**Comment by azazel75** [comment]
You could have at least left it commented

**Comment by eyJhb** [comment]
I see no reason for letting it stay as a comment :)
But making a module of this could be nice, but not something I am currently up for, I just use the configuration directly in my `configuration.nix`.

Anyways, case closed. If anyone see fit adding something like this as a module, feel free! :)

**Comment by danbst** [comment]
@azazel75 @eyJhb I'm going to ressurect this, but as an optional module option. This indeed shouldn't be default, but is useful for certain usecases.

**Comment by eyJhb** [comment]
It is useful yes, but there still is the normal possibility for adding it to the configuration.nix? But yeah, options would be nice. :)

https://github.com/eyJhb/dot/blob/master/dotfiles/nixos/configuration.nix#L292-L301

**Pull request merged**
