### PR TITLE
lenovo/t460s: add middle button config + comments

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
Up

**Comment by Ericson2314** [comment]
@ehmry might be AWAL, anybody else have push access? This is a newish repo so I don't think a full set of maintainers has been worked out.

**Comment by ehmry** [comment]
I just never get notified on pull requests.

**Comment by Ericson2314** [comment]
Oh, nevermind then. Yay!

**Comment by ehmry** [comment]
I wish I did though.

**Comment by DamienCassou** [comment]
@ehmry what is your "Watch" status? (big "Watch" button in the top of the page on the `nixos-hardware` project).

**Comment by ehmry** [comment]
Watching, its a bug.

**Pull request merged**
